quarkus.devservices.enabled=false
kafka.bootstrap.servers=localhost:9092
mp.messaging.outgoing.price-out.connector=smallrye-kafka
mp.messaging.outgoing.price-out.topic=prices
mp.messaging.outgoing.price-out.value.serializer=org.apache.kafka.common.serialization.DoubleSerializer
mp.messaging.incoming.price-in.connector=smallrye-kafka
mp.messaging.incoming.price-in.topic=prices
mp.messaging.incoming.price-in.value.deserializer=org.apache.kafka.common.serialization.DoubleDeserializer